### ISSUE TITLE
Fourier average vs Hankel-DMD out of phase

### ISSUE THREAD

**Issue by ahsteven** [arbabiha/DMD-for-ergodic-systems#1]
Hello Hassan,

Thank you very much for this work. It is very interesting. 

When I run the code the Fourier average and Hankel-DMD are 180 deg out of phase. In the figure in the paper they are exactly lined up. Why is Hankel-DMD flipped in this case?

**Comment by arbabiha** [comment]
Thanks for reaching out to me!

I just downloaded the code and ran it. It produced the right figure. Are you making any modifications when you run?

In any case, you should note that phase is relative: once you (implicitly or explicitly) set the phase of a point on the limit cycle, say x0, equal to zero, the algorithm should compute the phase of any initial condition relative to that point. So when we say two initial conditions are synchronized it means that they have the same phase (i.e. same color) with respect to x0. The purpose of the figure that compares with harmonic average is to show that Koopman eigenfunction (i.e. cos(i\theta) ) returned by Hankel-DMD is a pure sinusoid which has the same phase variation as harmonic average.

I hope this clarifies it, let me know if not.
